<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Promise</title>
</head>

<body>
	<script>
		class Hoge {

			init() {
				window.addEventListener('unhandledrejection', this.unhandledrejection.bind(this));
				window.addEventListener('rejectionhandled', this.rejectionhandled.bind(this));
			}

			unhandledrejection(e) {
				console.log('失敗が確定した時には、受け止めるcatchがありませんでした。');
			}

			rejectionhandled(e) {
				console.log('すでに失敗した後ですが、catchで受け止めされました。');
			}

			main() {
				console.log('main');
				const url1 = 'promise.json';
				const url2 = 'http://google.comm/promise.json';

				let p = fetch(url2);
				setTimeout(()=>{
					p.catch(()=>{});
				}, 1000);
			}

			async fetch2(url) {
				try {
					const result = await fetch(url);
					const json = await result.json();
					return json.data;
				}
				catch (e) {
					console.log('catch');
					console.log(e);
				}
				finally {
					console.log('finally');
				}
			}

			fetch(url) {
				let promise = fetch(url);
				promise = this.chain(promise);
				promise.then(e => {
					console.log("ok");
					return e['data'];
				}).then(e => {
					console.log(e);
					// return 'successed';
					throw new Error('errored');
				}).catch(e => {
					console.log(e);
					return "catched.";
				}).then(e => {
					console.log(e);
				});
			}

			chain(promise) {
				promise = promise.then(
					e => {
						console.log('sucess');
						return e.json();
					},
					e => {
						console.log('error');
						// throw new Error("test");
					},
				).catch(e => {
					console.log('catch');
				}).finally(e => {
					console.log('finally');
				});
				return promise;
			}
		}
		const hoge = new Hoge();
		hoge.init();
		hoge.main();
	</script>
</body>

</html>